FROM logstash:5
RUN logstash-plugin install logstash-output-email
RUN logstash-plugin install logstash-filter-clone
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
